### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow


In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences - we are applying ohe on it and later convert this into vector using embedding
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size - dimensions; increases vocab size takes more time
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] # here index corresponding to the words shows i.e. the value of 'the' at 25 index is 1
print(onehot_repr)

[[159, 36, 320, 386], [159, 36, 320, 268], [159, 336, 320, 416], [452, 238, 303, 269, 9], [452, 238, 303, 269, 85], [179, 159, 264, 320, 91], [478, 147, 219, 269]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences #used for pre and post padding
from tensorflow.keras.models import Sequential #for sequential NN

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 159  36 320 386]
 [  0   0   0   0 159  36 320 268]
 [  0   0   0   0 159 336 320 416]
 [  0   0   0 452 238 303 269   9]
 [  0   0   0 452 238 303 269  85]
 [  0   0   0 179 159 264 320  91]
 [  0   0   0   0 478 147 219 269]]


In [12]:
## 10 feature dimensions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_shape=(sent_length,)))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 159,  36, 320, 386], dtype=int32)

In [16]:
model.predict(np.array([embedded_docs[0]]))
# or print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 347ms/step


array([[[ 0.03982035, -0.00718755,  0.02850994,  0.02379457,
          0.02134409,  0.02839227,  0.02059858, -0.04821059,
          0.02313497, -0.00972692],
        [ 0.03982035, -0.00718755,  0.02850994,  0.02379457,
          0.02134409,  0.02839227,  0.02059858, -0.04821059,
          0.02313497, -0.00972692],
        [ 0.03982035, -0.00718755,  0.02850994,  0.02379457,
          0.02134409,  0.02839227,  0.02059858, -0.04821059,
          0.02313497, -0.00972692],
        [ 0.03982035, -0.00718755,  0.02850994,  0.02379457,
          0.02134409,  0.02839227,  0.02059858, -0.04821059,
          0.02313497, -0.00972692],
        [ 0.0029071 ,  0.03887271, -0.0342802 ,  0.031891  ,
         -0.04825634, -0.04089831,  0.01060897,  0.03221265,
         -0.0372591 ,  0.02442637],
        [ 0.04090414,  0.03599875, -0.01915281,  0.01204396,
         -0.00138298, -0.04917505,  0.01947888, -0.00517088,
          0.0302549 ,  0.00997609],
        [ 0.04828909,  0.02918318,  0.01908186,  0.0

In [17]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
[[[ 0.03982035 -0.00718755  0.02850994  0.02379457  0.02134409
    0.02839227  0.02059858 -0.04821059  0.02313497 -0.00972692]
  [ 0.03982035 -0.00718755  0.02850994  0.02379457  0.02134409
    0.02839227  0.02059858 -0.04821059  0.02313497 -0.00972692]
  [ 0.03982035 -0.00718755  0.02850994  0.02379457  0.02134409
    0.02839227  0.02059858 -0.04821059  0.02313497 -0.00972692]
  [ 0.03982035 -0.00718755  0.02850994  0.02379457  0.02134409
    0.02839227  0.02059858 -0.04821059  0.02313497 -0.00972692]
  [ 0.0029071   0.03887271 -0.0342802   0.031891   -0.04825634
   -0.04089831  0.01060897  0.03221265 -0.0372591   0.02442637]
  [ 0.04090414  0.03599875 -0.01915281  0.01204396 -0.00138298
   -0.04917505  0.01947888 -0.00517088  0.0302549   0.00997609]
  [ 0.04828909  0.02918318  0.01908186  0.0278451   0.02805109
   -0.01629151  0.02336006 -0.01843264 -0.04581523  0.03354527]
  [-0.01338951  0.00584473  0.02700399  0.0285606  -0.04747527
    0.022